name: Run Program

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build -t tcp-connection-kt .
      - name: Exec kotlin program
        run: docker run --rm --name tcp-connection-kt tcp-connection-kt
